import { it, expect } from "vitest";
import { BuilderState } from "../../builder/src/builder-state.js";
import { renderSectionEditor } from "../../builder/src/ui/section-editor.js";
import { renderWorkbook } from "../../src/core/renderer.js";
import { domToConfig } from "../../src/core/dom-config.js";
import { registerAllFields } from "../../src/fields/index.js";
import { exportWorkbookPdf } from "../../src/pdf/pdf-export.js";
import { importWorkbookPdf } from "../../src/pdf/pdf-import.js";
import { computeProgress } from "../../src/core/progress.js";
import { validateWorkbook } from "../../src/core/validation.js";
import { PDFDocument } from "pdf-lib";

registerAllFields();
it("authors standalone questions alongside sections and preserves them through HTML and PDF", async () => {
  const state = new BuilderState();
  state.setTitle("Standalone questions");
  const ws = state.addWorksheet();
  const editor = document.createElement("div");
  const render = () => renderSectionEditor(editor, state, ws.id, render, () => {});
  render();
  expect(editor.querySelectorAll(".builder-section-card")).toHaveLength(0);
  editor.querySelector(".builder-add-field-btn").click();
  const group = ws.sections[0];
  expect(group.unsectioned).toBe(true);
  state.updateField(ws.id, group.id, group.fields[0].id, { label: "First question" });
  const section = state.addSection(ws.id, { title: "Section" });
  state.addField(ws.id, section.id, { type: "short-text", label: "Inside section" });
  render();
  editor.querySelectorAll(".builder-add-field-btn")[2].click();
  expect(ws.sections[2].unsectioned).toBe(true);
  const restored = new BuilderState(state.toConfig());
  const mount = document.createElement("div");
  renderWorkbook(restored.toConfig(), mount);
  expect(mount.querySelectorAll("details")).toHaveLength(1);
  expect(mount.querySelectorAll("[data-unsectioned] input")).toHaveLength(2);
  const config = domToConfig(mount);
  expect(config.worksheets[0].sections.map(s => Boolean(s.unsectioned))).toEqual([true, false, true]);
  const pdf = await PDFDocument.load(await exportWorkbookPdf(restored.toConfig(), { worksheets: {} }));
  expect(pdf.getForm().getFields()).toHaveLength(3);
  pdf.getForm().getTextField(group.fields[0].id).setText("Imported answer");
  const imported = await importWorkbookPdf(restored.toConfig(), await pdf.save());
  expect(imported.data.worksheets[ws.id][group.fields[0].id]).toBe("Imported answer");
  state.updateField(ws.id, group.id, group.fields[0].id, { required: true });
  expect(validateWorkbook(state.toConfig(), {})).toHaveLength(1);
  expect(computeProgress(state.toConfig(), imported.data)).toEqual({ answered: 1, total: 1, percent: 100 });
  const field = group.fields[0];
  state.removeField(ws.id, group.id, field.id);
  expect(group.fields).toHaveLength(0);
  expect(ws.sections).not.toContain(group);
});
